services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES__PASSWORD:-Abc12345}
      TZ: "UTC"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - docker_stack
    restart: always

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Abc12345
    volumes:
      - mongo_data:/var/lib/mongodb/data
    ports:
      - 27018:27017
    networks:
      - docker_stack
    restart: always

  redis:
    image: redis:7.2
    command: redis-server --save 60 1 --loglevel warning --requirepass Abc12345
    volumes:
      - redis_data:/var/lib/redis/data
    ports:
      - '6381:6379'
    networks:
      - docker_stack
    restart: always

  rabbitmq:
    build:
      context: ./rabbitmq/docker
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/data
    ports:
      - 15673:15672
      - 5673:5672
    networks:
      - docker_stack
    restart: always

networks:
  docker_stack:
    external: true

volumes:
  postgres_data:
  mongo_data:
  redis_data:
  rabbitmq_data: