services:
  rabbitmq:
    container_name: rabbitmq
    build:
      context: ./docker
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/data
    ports:
      - 15673:15672
      - 5673:5672
    networks:
      - docker_stack
    restart: unless-stopped

networks:
  docker_stack:
    external: true

volumes:
  rabbitmq_data:
