services:
  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES__PASSWORD:-Abc12345}
      TZ: "UTC"
    #      PGTZ: "UTC"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - docker_stack
    restart: unless-stopped

networks:
  docker_stack:
    external: true

volumes:
  postgres_data:
