services:
  redis:
    container_name: redis
    image: redis:7.2
    command: redis-server --save 60 1 --loglevel warning --requirepass Abc12345
    volumes:
      - redis_data:/var/lib/redis/data
    ports:
      - '6381:6379'
    networks:
      - docker_stack
    restart: unless-stopped

networks:
  docker_stack:
    external: true

volumes:
  redis_data: