# Logging
loglevel warning

# Auth
requirepass Abc12345

# --- RDB ---
save 3600 1
save 300 100
save 60 10000
dbfilename dump.rdb

# --- AOF ---
appendonly yes
appendfilename "appendonly.aof"
appendfsync everysec
no-appendfsync-on-rewrite no
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb

# --- Hybrid (RDB preamble in AOF) ---
aof-use-rdb-preamble yes

# Data dir
dir /data
